name: '%Y-%m-%d-%H-%M-%S'

save_dir: './results/${name}/'

# Environment
seed: 0
devices: [0]

# Loggers
use_profiler: False
loggers:
  use_csv_logger: True
  use_wandb: False

# Model
use_pretrained: True
# pretrained_mast3r_path: './checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth'
# pretrained_mast3r_path: './pretrained/splatt3r_coarse.ckpt'
# pretrained_mast3r_path: './pretrained/splatt3r_3stage.ckpt'
# pretrained_mast3r_path: './checkpoints/splatt3r_coarse3_stage_256.ckpt'
pretrained_mast3r_path: './checkpoints/keep/splatt3r_coarse_256_128.ckpt'

# pretrained_mast3r_path: './checkpoints/keep/splatt3r_coarse=0_epoch=04.ckpt'
checkpoint_file_path: '/mnt/buzz_newhd/home/v4rl/splatt3r/checkpoints/'

grad_gaussian_dpt: False
grad_gaussian_256_dpt: False
grad_gaussian_128_dpt: False
grad_coarseness_prediction: True
coarseness_predictions: False
train_coarseness_prediction: True

use_lod: False
th_rgb: 0.3
th_depth: 0.5
resolution: 512
train_head_only: False
use_calib: True

# Data
data:
  root: '/mnt/buzz_newhd/home/v4rl/scannetpp-dataset/'
  batch_size: 1
  num_workers: 4
  resolution: [512, 512]
  epochs_per_train_epoch: 1 #12 #50 #10 #100 # How many times to sample from each scene each training epoch (helps avoid unnecessary Pytorch Lightning overhead)

# Optimization
opt:
  epochs: 10 #5 # 20
  lr: 0.00001
  weight_decay: 0.05
  gradient_clip_val: 0.5

loss:
  mse_loss_weight: 1.0
  lpips_loss_weight: 0.25
  mast3r_loss_weight: Null
  apply_mask: True
  average_over_mask: True

use_offsets: False
sh_degree: 1